chatFormat: "[coral][{0}[coral]]:[white] {1}"
strict:
  # Enabling this feature will only allow specific languages.
  enabled: false
  # Set the langauges you want to allow. (default: en)
  language: "en"

blacklist:
  # Set the word ban function.
  enabled: false
  # When enabling this function, a blacklist of words is read as a regular expression.
  regex: false