# Enter the server address where you have multiple servers.
address: 127.0.0.1
# Enter a available port.
port: 42600

# Set settings to synchronize settings between servers
sharing:
  # All servers use the same ban list. (default: false)
  ban: false
  # When this setting is turned on, players with broadcast permission can forward messages to all servers.
  broadcast: false
