# Block IP bands for known databases or VPNs.
vpn: false

# Block foo's client
foo: true

# Allow mobile users to access the server.
mobile: true

# Blocks access to all users except Steam users.
steam-only: false

# Set nickname minimal length
minimalName:
  enabled: false
  length: 4

# If the nickname and IP you are using do not match, the connection to the server will not be allowed.
# If mobile users allowed, problems will arise if mobile carrier distributes the same IP when using this option.
strict: false

# When attacked by an external program or modded client, you can protect the server and existing users by activating this setting.
block-new-user: false