# Enter the server address where you have multiple servers.
address: 127.0.0.1
# Enter a available port.
port: 42600
# If this setting is turned on, the number of servers connected using the hub command is totaled and displayed on the current server.
# default: false
count-all-servers: false

# Set settings to synchronize settings between servers
sharing:
  # All servers use the same ban list. (default: false)
  ban: false
  # When this setting is turned on, players with broadcast permission can forward messages to all servers.
  broadcast: false
