plugin:
  ## Plugin language
  lang: en

  ## Auto update
  autoUpdate: true

  ## Database URL
  ## Example) postgresql://127.0.0.1:5432/essentials
  database:
    url: sqlite:essential_database.db
    username: sa
    password: 123