config.created=Web configuration file has been created successfully.
config.loaded=Web configuration file has been loaded successfully.
config.parse.failed=Failed to parse the web configuration file.
event.plugin.load.failed=Failed to initialize the Web Service plugin.
event.plugin.loaded=Web Service plugin has been initialized successfully.
event.plugin.starting=Initializing the Web Service plugin...
web.server.started=Web server has started successfully on port {0}.
web.server.stopped=Web server has been stopped.