/* 예약된 table 이름과 linux 문제 해결 */
ALTER TABLE player RENAME TO players;
ALTER TABLE "data" RENAME TO plugin_data;
CREATE TABLE IF NOT EXISTS player_banned (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    names VARCHAR,
    ips VARCHAR,
    uuid VARCHAR(25),
    reason VARCHAR(256) DEFAULT 'Legacy ban',
    date BIGINT DEFAULT 0
);

INSERT INTO player_banned (names, uuid, reason)
SELECT '[||"' || data || '"||]', data, 'Legacy ban (name/UUID)'
FROM banned WHERE type = 0
GROUP BY data;

INSERT INTO player_banned (ips, reason)
SELECT '[||"' || data || '"||]', 'Legacy ban (IP)'
FROM banned WHERE type = 1
GROUP BY data;

DROP TABLE IF EXISTS banned;

/* 더이상 사용하지 않는 column 삭제 (존재할 때만) */
ALTER TABLE players DROP COLUMN IF EXISTS "FREEZE";
ALTER TABLE players DROP COLUMN IF EXISTS "HUD";
ALTER TABLE players DROP COLUMN IF EXISTS "TPP";
ALTER TABLE players DROP COLUMN IF EXISTS "tppTeam";
ALTER TABLE players DROP COLUMN IF EXISTS "LOG";
ALTER TABLE players DROP COLUMN IF EXISTS "oldUUID";
ALTER TABLE players DROP COLUMN IF EXISTS "duplicateName";
ALTER TABLE players DROP COLUMN IF EXISTS "TRACKING";
ALTER TABLE players DROP COLUMN IF EXISTS "lastPlayedWorldId";
ALTER TABLE players DROP COLUMN IF EXISTS "totalJoinCount";
ALTER TABLE players DROP COLUMN IF EXISTS "totalKickCount";
ALTER TABLE players DROP COLUMN IF EXISTS "animatedName";
ALTER TABLE players DROP COLUMN IF EXISTS "currentPlayTime";

/* RDBMS Linux 기본 설정으로 인한 이름 변경 (원본이 따옴표 camelCase임) */
ALTER TABLE players ALTER COLUMN "blockPlaceCount" RENAME TO block_place_count;
ALTER TABLE players ALTER COLUMN "blockBreakCount" RENAME TO block_break_count;
ALTER TABLE players ALTER COLUMN "firstPlayDate" RENAME TO first_played;
ALTER TABLE players ALTER COLUMN "lastLoginTime" RENAME TO last_played;
ALTER TABLE players ALTER COLUMN "languageTag" RENAME TO language_tag;
ALTER TABLE players ALTER COLUMN "totalPlayTime" RENAME TO total_played;
ALTER TABLE players ALTER COLUMN "attackModeClear" RENAME TO attack_clear;
ALTER TABLE players ALTER COLUMN "pvpVictoriesCount" RENAME TO pvp_win_count;
ALTER TABLE players ALTER COLUMN "pvpDefeatCount" RENAME TO pvp_lose_count;
ALTER TABLE players ALTER COLUMN "pvpEliminationTeamCount" RENAME TO pvp_eliminated_count;
ALTER TABLE players ALTER COLUMN "mvpTime" RENAME TO pvp_mvp_count;
ALTER TABLE players ALTER COLUMN "accountID" RENAME TO account_id;
ALTER TABLE players ALTER COLUMN "accountPW" RENAME TO account_pw;
ALTER TABLE players ALTER COLUMN "DISCORD" RENAME TO discord_id;
ALTER TABLE players ALTER COLUMN "MUTE" RENAME TO chat_muted;
ALTER TABLE players ALTER COLUMN "showLevelEffects" RENAME TO effect_visibility;
ALTER TABLE players ALTER COLUMN "effectLevel" RENAME TO effect_level;
ALTER TABLE players ALTER COLUMN "effectColor" RENAME TO effect_color;
ALTER TABLE players ALTER COLUMN "hideRanking" RENAME TO hide_ranking;
ALTER TABLE players ALTER COLUMN "STRICT" RENAME TO strict_mode;
ALTER TABLE players ALTER COLUMN "lastLoginDate" RENAME TO last_login_date;
ALTER TABLE players ALTER COLUMN "lastLeaveDate" RENAME TO last_logout_date;
ALTER TABLE players ALTER COLUMN "lastPlayedWorldName" RENAME TO last_played_world_name;
ALTER TABLE players ALTER COLUMN "lastPlayedWorldMode" RENAME TO last_played_world_mode;
ALTER TABLE players ALTER COLUMN "isConnected" RENAME TO is_connected;
ALTER TABLE players ALTER COLUMN "banTime" RENAME TO ban_expire_date;
ALTER TABLE players ALTER COLUMN "joinStacks" RENAME TO attendance_days;

/* Date-Time 변환 */
ALTER TABLE PLAYERS ADD COLUMN first_played_tmp TIMESTAMP(9);
ALTER TABLE PLAYERS ADD COLUMN last_played_tmp TIMESTAMP(9);
UPDATE PLAYERS SET
                   first_played_tmp = CASE WHEN first_played IS NOT NULL AND first_played != 0 THEN DATEADD('MS', first_played, DATE '1970-01-01') ELSE CURRENT_TIMESTAMP(9) END,
                   last_played_tmp = CASE WHEN last_played IS NOT NULL AND last_played != 0 THEN DATEADD('MS', last_played, DATE '1970-01-01') ELSE CURRENT_TIMESTAMP(9) END;
ALTER TABLE PLAYERS DROP COLUMN first_played;
ALTER TABLE PLAYERS DROP COLUMN last_played;
ALTER TABLE PLAYERS ALTER COLUMN first_played_tmp RENAME TO first_played;
ALTER TABLE PLAYERS ALTER COLUMN last_played_tmp RENAME TO last_played;

ALTER TABLE PLAYERS ADD COLUMN last_login_date_tmp TIMESTAMP(9);
UPDATE PLAYERS SET last_login_date_tmp = (
    CASE
        WHEN last_login_date REGEXP '^\d{4}-\d{2}-\d{2}.*'
            THEN CAST(last_login_date AS TIMESTAMP(9))
        ELSE CURRENT_TIMESTAMP(9)
        END
    );
ALTER TABLE PLAYERS DROP COLUMN last_login_date;
ALTER TABLE PLAYERS ALTER COLUMN last_login_date_TMP RENAME TO last_login_date;

ALTER TABLE PLAYERS ADD COLUMN last_logout_date_tmp TIMESTAMP(9);
UPDATE PLAYERS SET last_logout_date_tmp = (
    CASE
        WHEN last_logout_date REGEXP '^\d{4}-\d{2}-\d{2}.*'
            THEN CAST(last_logout_date AS TIMESTAMP(9))
        ELSE NULL
        END
    );
ALTER TABLE PLAYERS DROP COLUMN last_logout_date;
ALTER TABLE PLAYERS ALTER COLUMN last_logout_date_tmp RENAME TO last_logout_date;

ALTER TABLE PLAYERS ADD COLUMN ban_expire_date_tmp TIMESTAMP(9);
UPDATE PLAYERS SET ban_expire_date_tmp = (
    CASE
        WHEN ban_expire_date REGEXP '^\d{4}-\d{2}-\d{2}.*'
            THEN CAST(ban_expire_date AS TIMESTAMP(9))
        ELSE NULL
        END
    );
ALTER TABLE PLAYERS DROP COLUMN ban_expire_date;
ALTER TABLE PLAYERS ALTER COLUMN ban_expire_date_tmp RENAME TO ban_expire_date;

ALTER TABLE players ALTER COLUMN first_played SET DEFAULT CURRENT_TIMESTAMP(9);
ALTER TABLE players ALTER COLUMN last_played SET DEFAULT CURRENT_TIMESTAMP(9);
ALTER TABLE players ALTER COLUMN last_login_date SET DEFAULT CURRENT_TIMESTAMP(9);

/* Set DEFAULT values for all columns */
ALTER TABLE players ALTER COLUMN language_tag SET DEFAULT 'en';
ALTER TABLE players ALTER COLUMN block_place_count SET DEFAULT 0;
ALTER TABLE players ALTER COLUMN block_break_count SET DEFAULT 0;
ALTER TABLE players ALTER COLUMN total_played SET DEFAULT 0;
ALTER TABLE players ALTER COLUMN attack_clear SET DEFAULT 0;
ALTER TABLE players ALTER COLUMN pvp_win_count SET DEFAULT 0;
ALTER TABLE players ALTER COLUMN pvp_lose_count SET DEFAULT 0;
ALTER TABLE players ALTER COLUMN pvp_eliminated_count SET DEFAULT 0;
ALTER TABLE players ALTER COLUMN pvp_mvp_count SET DEFAULT 0;
ALTER TABLE players ALTER COLUMN account_id SET DEFAULT NULL;
ALTER TABLE players ALTER COLUMN account_pw SET DEFAULT NULL;
ALTER TABLE players ALTER COLUMN discord_id SET DEFAULT NULL;
ALTER TABLE players ALTER COLUMN chat_muted SET DEFAULT FALSE;
ALTER TABLE players ALTER COLUMN effect_visibility SET DEFAULT FALSE;
ALTER TABLE players ALTER COLUMN effect_level SET DEFAULT NULL;
ALTER TABLE players ALTER COLUMN effect_color SET DEFAULT NULL;
ALTER TABLE players ALTER COLUMN hide_ranking SET DEFAULT FALSE;
ALTER TABLE players ALTER COLUMN strict_mode SET DEFAULT FALSE;
ALTER TABLE players ALTER COLUMN last_logout_date SET DEFAULT NULL;
ALTER TABLE players ALTER COLUMN last_played_world_name SET DEFAULT NULL;
ALTER TABLE players ALTER COLUMN last_played_world_mode SET DEFAULT NULL;
ALTER TABLE players ALTER COLUMN is_connected SET DEFAULT FALSE;
ALTER TABLE players ALTER COLUMN ban_expire_date SET DEFAULT NULL;
ALTER TABLE players ALTER COLUMN attendance_days SET DEFAULT 0;
ALTER TABLE players ALTER COLUMN permission SET DEFAULT 'default';
ALTER TABLE players ALTER COLUMN level SET DEFAULT 0;
ALTER TABLE players ALTER COLUMN exp SET DEFAULT 0;
ALTER TABLE players ALTER COLUMN status SET DEFAULT '{}';

/* Set NOT NULL for datetime columns */
ALTER TABLE players ALTER COLUMN first_played SET NOT NULL;
ALTER TABLE players ALTER COLUMN last_played SET NOT NULL;
ALTER TABLE players ALTER COLUMN last_login_date SET NOT NULL;

/* Drop NOT NULL constraint for nullable columns */
ALTER TABLE players ALTER COLUMN account_id SET NULL;
ALTER TABLE players ALTER COLUMN account_pw SET NULL;
ALTER TABLE players ALTER COLUMN discord_id SET NULL;
ALTER TABLE players ALTER COLUMN effect_level SET NULL;
ALTER TABLE players ALTER COLUMN effect_color SET NULL;
ALTER TABLE players ALTER COLUMN last_logout_date SET NULL;
ALTER TABLE players ALTER COLUMN last_played_world_name SET NULL;
ALTER TABLE players ALTER COLUMN last_played_world_mode SET NULL;
ALTER TABLE players ALTER COLUMN ban_expire_date SET NULL;
ALTER TABLE players ALTER COLUMN status SET NULL;

/* Initialize NULL values for existing rows */
UPDATE players SET first_played = CURRENT_TIMESTAMP(9) WHERE first_played IS NULL;
UPDATE players SET last_played = CURRENT_TIMESTAMP(9) WHERE last_played IS NULL;
UPDATE players SET language_tag = 'en' WHERE language_tag IS NULL OR language_tag = '';
UPDATE players SET permission = 'default' WHERE permission IS NULL OR permission = '';
UPDATE players SET block_place_count = 0 WHERE block_place_count IS NULL;
UPDATE players SET block_break_count = 0 WHERE block_break_count IS NULL;
UPDATE players SET total_played = 0 WHERE total_played IS NULL;
UPDATE players SET attack_clear = 0 WHERE attack_clear IS NULL;
UPDATE players SET pvp_win_count = 0 WHERE pvp_win_count IS NULL;
UPDATE players SET pvp_lose_count = 0 WHERE pvp_lose_count IS NULL;
UPDATE players SET pvp_eliminated_count = 0 WHERE pvp_eliminated_count IS NULL;
UPDATE players SET pvp_mvp_count = 0 WHERE pvp_mvp_count IS NULL;
UPDATE players SET level = 0 WHERE level IS NULL;
UPDATE players SET exp = 0 WHERE exp IS NULL;
UPDATE players SET chat_muted = FALSE WHERE chat_muted IS NULL;
UPDATE players SET effect_visibility = FALSE WHERE effect_visibility IS NULL;
UPDATE players SET hide_ranking = FALSE WHERE hide_ranking IS NULL;
UPDATE players SET strict_mode = FALSE WHERE strict_mode IS NULL;
UPDATE players SET is_connected = FALSE WHERE is_connected IS NULL;
UPDATE players SET attendance_days = 0 WHERE attendance_days IS NULL;
UPDATE players SET status = '{}' WHERE status IS NULL OR status = '';

/* 새 데이터 추가 */
ALTER TABLE players ADD COLUMN wave_clear integer DEFAULT 0 NOT NULL AFTER attack_clear;
ALTER TABLE players ADD COLUMN is_banned boolean DEFAULT false NOT NULL AFTER is_connected;
ALTER TABLE plugin_data ADD COLUMN id integer;
ALTER TABLE plugin_data ADD COLUMN database_version integer;
ALTER TABLE plugin_data ADD COLUMN hub_map_name text;

UPDATE players SET wave_clear = 0 WHERE wave_clear IS NULL;
UPDATE players SET is_banned = false WHERE is_banned IS NULL;

UPDATE plugin_data SET id = 1 WHERE id IS NULL;
UPDATE plugin_data SET database_version = 4 WHERE database_version IS NULL;

/* 더이상 사용되지 않는 Table 삭제 */
DROP TABLE IF EXISTS db;

/* players 테이블에 id 컬럼 추가 (PLAYER_ACHIEVEMENTS 테이블의 외래 키 제약 조건을 위해 필요) */
ALTER TABLE players ADD COLUMN IF NOT EXISTS id BIGINT AUTO_INCREMENT PRIMARY KEY;

/* 새 테이블 추가 (만약 존재하지 않는 경우) */
CREATE TABLE IF NOT EXISTS PLAYER_ACHIEVEMENTS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    player_id BIGINT NOT NULL,
    achievement_name VARCHAR(100) NOT NULL,
    completed_at TIMESTAMP(9) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PLAYER_ACHIEVEMENTS_PLAYER_ID__ID FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
